### ISSUE TITLE
Bitcoin hack

### ISSUE THREAD

**Issue by Ogsmallz101** [Py-Project/Bitcoin-wallet-cracker#11]
How can i decrypt a wallet and access the funds?

**Comment by BitcoinBillionairee** [comment]
send me the wallet details and I can do it for you :)

**Comment by Chizzy06** [comment]
Which wallet please

On Sep 25, 2021 4:50 PM, "BitcoinBillionairee" ***@***.***>
wrote:

send me the wallet details and I can do it for you :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adrijano/Bitcoin-wallet-cracker/issues/11#issuecomment-927139857>,
or unsubscribe

**Comment by BitcoinBillionairee** [comment]
The one that you got when you ran the cracker and it came up with the Bingo message , the one you're trying to open.

**Comment by BitcoinBillionairee** [comment]
The one that you got when you ran the cracker and it came up with the Bingo message , the one you're trying to open.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BitcoinBillionairee** [comment]
* the one that you're trying to access the funds of

**Comment by Chizzy06** [comment]
3QTUxAKmHqLAkvAjSvPxYoi5yUVRPQm2Cx

That is the address

Please reply with your telegram username or Whatsapp number so that we Can
chat

**Comment by BitcoinBillionairee** [comment]
my telegram is understannnd777

**Comment by BitcoinBillionairee** [comment]
please comment your telegram username or directly message mine
